defaults:
  - train_diffusion
  - _self_

logger:
  name: eval_diffusion

model:
  path: /home/baldeeb/Code/nocs-diffusion/checkpoints/nocs-diffusion/train_diffusion/2024-09-07_12-58-39/0000_038000.pth