defaults:
  - train_diffusion
  - _self_


log_locally: true
logger:
  name: eval_diffusion

model:
  path: /workspace/nocs-diffusion/checkpoints/nocs-diffusion/train_diffusion/2024-06-30_10-59-09/0000_021000.pth