defaults:
  - logging
  - model@model.model: cloud_encoder
  - dataloader: shapenet
  - _self_

device: cuda:0

logger:
  name:  eval_depth_vae

model:
  _target_:  nocs_diffusion.models.load_model
  # model: loaded in defaults

  # path: /home/baldeeb/Code/nocs-diffusion/checkpoints/nocs-diffusion/depth_vae/2024-04-11_10-47-08/0000_099999.pth
  # path: /home/baldeeb/Code/nocs-diffusion/checkpoints/nocs-diffusion/train_depth_vae/2024-05-03_15-57-20/0000_009999.pth
  path: /home/baldeeb/Code/nocs-diffusion/checkpoints/nocs-diffusion/train_depth_vae/2024-05-07_21-01-28/0000_009999.pth
  # path: /workspace/nocs-diffusion/checkpoints/nocs-diffusion/train_depth_vae/2024-06-29_15-17-49/0000_099999.pth



# Data
image_size: ${dataloader.renderer.image_size}
dataloader:
  renderer:
    batch_size: 64

# Models: loaded in defaults