defaults:
  - depth_vae
  - _self_

logger:
  name:    depth_vae_eval

# Load Models
model:
  path: /home/baldeeb/Code/nocs-diffusion/checkpoints/nocs-diffusion/depth_vae/2024-03-18_10-16-23/0000_099999.pth