defaults:
  - logging
  - model: cloud_encoder
  - dataloader: shapenet
  - _self_

device: cuda:0

logger:
  name:    train_depth_vae

# Data
image_size: ${dataloader.renderer.image_size}
dataloader:
  renderer:
    batch_size: 64

# Training
num_steps: 50000          # Epochs to train for
steps_before_save: 100  # Batches before saving a checkpoint
steps_before_eval: 50   # Batches before evaluating
num_eval_batches: 5       # Batches to evaluate on

# Models: loaded in defaults

# Optimizer
lr: 1e-3
lr_warmup_steps: 50